### ISSUE TITLE
The selection cursor is not visible on dark background

### ISSUE THREAD

**Issue by Saucistophe** [mustafaozhan/Breeze-Adapta-Cursor#10]
As displayed on the readme page, the crosshair cursor is not visible on a dark background:

![image](https://user-images.githubusercontent.com/7082839/98914494-0a041c00-24c9-11eb-86c7-e06a4733244c.png)

The biggest problem with this is when taking a screen shot of a specific area under linux mint:
![image](https://user-images.githubusercontent.com/7082839/98914951-9282bc80-24c9-11eb-9f13-47424adf70f2.png)

**Comment by mustafaozhan** [comment]
Hello @Saucistophe can you please add a screenshoot of how it looks in your PR ? I do not have a Linux machine now and can not see how it looks like.
