### ISSUE TITLE
Update Error

### ISSUE THREAD

**Issue by btd1337** [mustafaozhan/Breeze-Adapta-Cursor#3]
When u try update this error ocurrs

```
mkdir: cannot create directory ‘/usr/share/icons/Breeze-Adapta’: File exists
mv: inter-device move failed: 'cursors' to '/usr/share/icons/Breeze-Adapta/cursors'; unable to remove target: Directory not empty
```

**Comment by mustafaozhan** [comment]
Solved with [commit #620f1c4](https://github.com/mustafaozhan/Breeze-Adapta-Cursor/commit/620f1c4ce5e67d6ce419ecda3a886c66007da829) and [commit #8675719](https://github.com/mustafaozhan/Breeze-Adapta-Cursor/commit/86757193fb0a3acd47976354d6eea330ea7c7c02)
