### ISSUE TITLE
Hands out of ass

### ISSUE THREAD

**Issue by Feresey** [mustafaozhan/Breeze-Adapta-Cursor#7]
Please look at your [file](https://github.com/mustafaozhan/Breeze-Adapta-Cursor/blob/master/install.sh)
remove these unnecessary semicolons at the ends of the lines AND REPLACE cd .. and mv * using relative paths. PLEASE

**Comment by mustafaozhan** [comment]
Hello I am not  able to test these values since I do not have my Linux computer with me. Please do not hesitate to create an PR
