### ISSUE TITLE
Typing mistake in install.sh

### ISSUE THREAD

**Issue by KariNarhi** [mustafaozhan/Breeze-Adapta-Cursor#9]
I know you have not been working on this for a year (according to commit history), but I want to mention this.

After executing `cd /dev/shm` and cloning the git repo, the install script tries to execute command `cd Breeze-Adapta` (Line 5 in install.sh), even though the name of the directory should be Breeze-Adapta-Cursor.

Because of this error, the install script fails to move into the correct directory which contains the **.theme** files and **cursors** directory and produces only empty Breeze-Adapta directory in `/usr/share/icons/Breeze-Adapta/`.

In terminal it shows an error that there are no .theme files or cursors directory since the earlier `cd Breeze-Adapta` command failed and the install script is still actually in `/dev/shm` directory.

 `cd Breeze-Adapta` needs to be re-written as  `cd Breeze-Adapta-Cursor`

**Comment by mustafaozhan** [comment]
Thank you for reporting this it is fixed now :)
